name: todo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_slider_drawer: ^2.1.1
  flutter_svg: ^2.1.0
  ftoast: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^1.4.0
  panara_dialogs: ^0.1.2
  uuid: ^3.0.5

dev_dependencies:
  build_runner: 2.0.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/img/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
